import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/eiointhcngcli">EIOinthcngcli</Link>
        </li>
        <li>
          <Link to="/mnhnhthaotcxera">Mnhnhthaotcxera</Link>
        </li>
        <li>
          <Link to="/inphiuvtrchneio">InphiuvtrchnEIO</Link>
        </li>
        <li>
          <Link to="/truyvnthngtincontainermdropdown">
            Truyvnthngtincontainermdropdown
          </Link>
        </li>
        <li>
          <Link to="/truyvnthngtincontainer">Truyvnthngtincontainer</Link>
        </li>
        <li>
          <Link to="/inphiueir">InphiuEIR</Link>
        </li>
        <li>
          <Link to="/mnhnhch">Mnhnhch</Link>
        </li>
        <li>
          <Link to="/adminngnhp">ADMINngnhp</Link>
        </li>
        <li>
          <Link to="/truyvnlnhgiaonhn">Truyvnlnhgiaonhn</Link>
        </li>
        <li>
          <Link to="/inphiuvtrchachneio">InphiuvtrChachnEIO</Link>
        </li>
        <li>
          <Link to="/cuhnhlnthitbngoivi">Cuhnhlnthitbngoivi</Link>
        </li>
        <li>
          <Link to="/xcnhneio">XcnhnEIO</Link>
        </li>
        <li>
          <Link to="/ineiothcng">InEIOthcng</Link>
        </li>
        <li>
          <Link to="/chititcontainer">ChititContainer</Link>
        </li>
        <li>
          <Link to="/mnhnhthaotcxevo">Mnhnhthaotcxevo</Link>
        </li>
        <li>
          <Link to="/truyvniuchnhxemoc">Truyvniuchnhxemoc</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
